zuul:
  routes:
    myConsumer: /myConsumer/**
    flowControlProvider: /flowControlProvider/**
    isolationProvider: /isolationProvider/**

# disable netflix eurkea since it's not used for service discovery
ribbon:
  eureka:
    enabled: false

server:
  port: 8889

servicecomb:
  tracing:
    enabled: false
